# -*- coding: utf-8 -*-
"""SuperStore(Week 6).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10NKwGGUO_AJJQdpYTP_oWbJuw7gLflr2

# **Indian Cars: Data Analysis and Visualization**

---
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv('/content/train (1).csv')

df.head()

df.columns

df.dtypes

df.shape

df.info(verbose =True)

df.isna().sum()

state_with_empty_postal = df.loc[df['Postal Code'].isnull(), 'State'].unique()

print(state_with_empty_postal)

city_empty_postal = df.loc[df['Postal Code'].isnull(), 'City'].unique()

print(city_empty_postal)

country_empty_postal = df.loc[df['Postal Code'].isnull(), 'Country'].unique()

print(country_empty_postal)

df['Postal Code'].fillna(05401.0, inplace=True)
df['Postal Code'] = df['Postal Code'].astype(int)

df.isna().sum()

col = ['Order Date', 'Ship Date']

df[col] = df[col].apply(lambda col: pd.to_datetime(col, format='%d/%m/%Y', errors='coerce'))

df.dtypes

df

"""# Univariate analysis

---


"""

sales = df.groupby('Category')['Sales'].sum().reset_index()
plt.pie(sales['Sales'], labels = sales['Category'] ,autopct = '%1.3f%%')
plt.title('Sales Distribution VS Category')
plt.show()

plt.figure(figsize=(20,8))
plt.subplot(2, 1, 2)
plt.hist(df['Sub-Category'], bins=20, edgecolor='black', alpha=0.7, color='green')
plt.title('Sub-category')
plt.xticks(rotation=90)
plt.show()

df['Order Year'] = df['Order Date'].dt.year
yearly = df.groupby('Order Year')['Sales'].sum().reset_index()

plt.figure(figsize=(8, 6))
plt.plot(yearly['Order Year'], yearly['Sales'], marker='o', linestyle='-')
plt.title('Overall Sales VS Time')
plt.xlabel('Year')
plt.ylabel('Total Sales')
plt.xticks(yearly['Order Year'].astype(int))
plt.show()

"""# Bivariate analysis


---



"""

plt.figure(figsize=(20,5))
sns.barplot(data = df, x='Sub-Category', y = 'Sales')
plt.show()

plt.figure(figsize=(8,6))
sns.lineplot(x ='Region', y = 'Sales', hue = 'Category', data = df, palette = 'bright')
plt.title('Sales Trends Vs Region')
plt.legend(title = 'Category')
plt.show()

category = df.groupby('Ship Mode')['Sales'].sum().reset_index()
plt.pie(category['Sales'], labels = category['Ship Mode'],autopct = '%1.3f%%')
plt.title('Sales Distribution by Shipping Mode')
plt.show()

df['Month'] = df['Order Date'].dt.month
df['Year'] = df['Order Date'].dt.year
df['Quarter'] = df['Order Date'].dt.quarter

sales_monthly = df.groupby('Month')['Sales'].sum().reset_index()
sales_yearly = df.groupby('Year')['Sales'].sum().reset_index()
sales_quarterly = df.groupby('Quarter')['Sales'].sum().reset_index()

sns.lineplot(data = sales_monthly, x = 'Month', y = 'Sales', marker = 'o', color = 'indigo')
plt.title('Monthly Sales')
plt.show()

sns.lineplot(data = sales_yearly, x = 'Year', y = 'Sales', marker = 'o', color = 'orangered')
plt.title('Yearly Sales')
plt.show()

sns.lineplot(data = sales_quarterly, x = 'Quarter', y = 'Sales', marker = 'o', color = 'forestgreen')
plt.title('Quarterly Sales')
plt.show()

col1 = ['Segment', 'Sales', 'Year']
col1 = df[col1]

plt.figure(figsize=(8,6))
segment_sales = col1.groupby(['Segment','Year'])['Sales'].sum().reset_index()
sns.barplot(x = 'Year', y = 'Sales', hue = 'Segment', data = segment_sales)
plt.title('Sales Trends for different Segments')
plt.show()

col2 = ['Product Name', 'Sales']
col2 = df[col2]

product_sales = col2.groupby('Product Name')['Sales'].sum().reset_index()
product_sales = product_sales.sort_values(by='Sales', ascending = False)

barplot = sns.barplot(x = 'Sales', y = 'Product Name', data = product_sales.head(10),  palette = 'magma')
plt.title('Top 10 Products By Sales')

for index, value in enumerate(product_sales['Sales'].head(10)):
  barplot.text(value, index, f'{value:,.2f}', ha = 'right', va = 'center')

